### ISSUE TITLE
Mapping array values

### ISSUE THREAD

**Issue by anyav77** [susanBuck/e15-spring20#11]
I'm working on the letter shift challenge for Project 1.  
I would appreciate any feedback on this code.  I'm trying to map the array values or extract the keys, so that I can increment the letters:

```php
function letterShift($inputString)
{
    $alphabet = array('a', 'b', 'c', 'd');
    $letters = str_split($inputString);
    foreach ($letters as $key => $value) {
        if (in_array($value, $alphabet)) {
            // need to map letters to the alphabet by key
            // how to determine the key in the alphabet array?
            //$key++;
            $letters = next($alphabet);  
            var_dump($letters);
        }
    }
}
```

**Comment by kreinholz** [comment]
How about converting the letters to integers (there's a built-in php function that does this), then shifting them before converting them back into letters? (There's another built-in php function that converts integers to their corresponding ASCII character). Grab an ASCII table to see what integers each letter (both uppercase and lowercase) maps to.

I think you'll find this makes for a simpler loop...

**Comment by susanBuck** [comment]
@anyav77 - I believe PHP's [array_search](https://www.php.net/manual/en/function.array-search.php) is what you're looking for.

It will search an array for a given value and return the key/position of that value if it's found.

Using ASCII mapping as @kreinholz suggests is another similar/alternative approach to the problem. Lots of different ways to attack this task. : )

**Comment by anyav77** [comment]
Thank you!

I was able to get it partially working with array_search:

```php
function letterShift($inputString)
{
    $alphabet = array('a', 'b', 'c', 'd');
    $flippedalphabet = array_flip($alphabet);
    $letters = str_split($inputString);
    foreach ($letters as $key => $value) {
        if (in_array($value, $alphabet)) {
            // convert letters to numbers
            // add 1
            // convert letters back
            // or
            $key = 1+(array_search($value, $alphabet)); // returns the keys of the shifted letters
            $value = array_search($key, $flippedalphabet);
            var_dump($letters);
        }
        //var_dump($value); // returns shifted letters
    }
}
'''
But the ASCII method turned to be easier, indeed.
