### ISSUE TITLE
Week 5: Question 9 - How can Controllers can be created in a Laravel project? [question dropped]

### ISSUE THREAD

**Issue by RGPhD** [susanBuck/e15-spring20#13]
Dear Professor @susanBuck,

Week 5 Question 9 asks: **What are two ways in which Controllers can be created in your Laravel project?**  Is it okay to select either one of the two ways you discuss in the video and notes, since the answer choices are radio buttons?  Or should I be digging deeper and selecting the best way?

Thank you kindly,

Robelyn

**Comment by susanBuck** [comment]
Hi @RGPhD - That questions is not configured correctly - it should be a multi-option question. I'll fix it now and let you know when it's corrected. Thanks for pointing this out.

**Comment by susanBuck** [comment]
Canvas would not let me change the question type, so I rewrote the question so it worked with radio buttons. But only students who haven't started the assignment yet will see this updated version.

**Given this, I'm going to toss out this question when grading. So you can choose any option and you'll get full credit.**

Sorry for the confusion!

And, just to clarify, yes there are two ways to create a controller:

1) Via the Artisan command `make:controller`
2) By manually creating a new Controller class file in `/app/Http/Controllers/`

**Comment by RGPhD** [comment]
Thank you.
