### ISSUE TITLE
Composer - Cannot create cache directory

### ISSUE THREAD

**Issue by smsummers1** [susanBuck/e15-spring20#14]
I hope I am not looking over something terribly obvious, but I can't figure out what is going on.  When I create a new Laravel project via the command line I get the following highlighted in bright green on my terminal (Mac) window:

**Cannot create cache directory /Users/shawna/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache**

**Cannot create cache directory /Users/shawna/.composer/cache/files/, or directory is not writable. Proceeding without cache**

It still creates my project and everything seems to work fine, but would really like to fix this issue.  Any thoughts or resources I should try?

Thanks.  :)

**Comment by budostylz** [comment]
I'm not familiar with Mac machines but this sounds like a permissions issue. Try checking out the links below for troubleshooting the permissions. Hope this helps:

(Scroll to Cache permission error when creating a new Laravel project with Composer)
https://hesweb.dev/e15/notes/laravel/new-laravel-app)

Permissions Reference
https://hesweb.dev/e15/notes/command-line/permissions

**Comment by susanBuck** [comment]
@budostylz is correct! Here's a direct link to the section of the notes they referred to: <https://hesweb.dev/e15/notes/laravel/new-laravel-app#cache-permission-error-when-creating-a-new-laravel-project-with-composer>.

**Comment by smsummers1** [comment]
I feel a bit silly for missing that in the notes.  

All is working properly now.  

Many thanks!!
