### ISSUE TITLE
Create Aliases in Cmder?

### ISSUE THREAD

**Issue by budostylz** [susanBuck/e15-spring20#15]
I must be missing something in the notes or getting old, LoL. How do you go about creating aliases in Cmder?

**Comment by susanBuck** [comment]
Add them/edit them in `c:\cmder-master\config\user_aliases.cmd`, then restart Cmder to have it recognize the changes. : )

Ref: https://hesweb.dev/e15/notes/command-line/windows-cmder#aliases

**Comment by susanBuck** [comment]
Closed this thread out - but feel free to re-open or start a new thread if your aliases aren't working.

**Comment by budostylz** [comment]
Thanks Susan. V/r

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
