### ISSUE TITLE
Project 2 Feedback Request

### ISSUE THREAD

**Issue by anyav77** [susanBuck/e15-spring20#16]
I would like to get feedback on my Project 2 concept.  I want to link it to a real-world project I'm building.  It is a marketplace website where sellers get commissions.  Currently, the commissions are processed manually behind the scenes.  I'm hoping to build a portal where sellers can manage their account and view the commissions.  So, this is a prototype commissions calculator:

![Commissions_Calculator](https://user-images.githubusercontent.com/1045307/75648713-c18c2300-5c05-11ea-90ae-414dc4c5bcc5.png)

**Comment by susanBuck** [comment]
Hi @anyav77 - 

If you're looking for feedback as whether this is a good fit for P2 - yup, it's perfect. Covers all the bases and nice that it has a real-world application.

If you're looking for more feedback beyond that - i.e. interface, execution, etc., let us know. : )

**Comment by janenycxo** [comment]
HI Susan,

What are your thoughts on creating a BMI calculator with these 3 inputs-
1. Select if you are Male/Female
2. Enter your weight
3. Enter your height
Calculate BMI

**Comment by susanBuck** [comment]
Hi @janenycxo - That'd work! Just make sure there are three unique input types. Example:

+ Male/Female could be radios (1)
+ Weight could be a regular text input (2)
+ Height could be two dropdowns - one for feet, one for inches (3)

One word of caution - there are lots of BMI calculators online, so I'd avoid searches like *PHP BMI calculator* as it'll take out the fun of writing the functionality yourself. Searching for *BMI formula* and adapting that into PHP would be fair game though. 👍 (This tip isn't specific to just a BMI calculator - applies to any sort of calculator)

**Comment by janenycxo** [comment]
> Hi @janenycxo - That'd work! Just make sure there are three unique input types. Example:
> 
> * Male/Female could be radios (1)
> * Weight could be a regular text input (2)
> * Height could be two dropdowns - one for feet, one for inches (3)
> 
> One word of caution - there are lots of BMI calculators online, so I'd avoid searches like _PHP BMI calculator_ as it'll take out the fun of writing the functionality yourself. Searching for _BMI formula_ and adapting that into PHP would be fair game though. 👍 (This tip isn't specific to just a BMI calculator - applies to any sort of calculator)

@susanBuck, great!! I will keep those in mind when I start working on P2, thank you!

**Comment by anyav77** [comment]
Could you provide feedback on the HTML version?  

http://e15p2.atozez.com/

Should I avoid type="number" in the HTML form?

> Hi @anyav77 -
> 
> If you're looking for feedback as whether this is a good fit for P2 - yup, it's perfect. Covers all the bases and nice that it has a real-world application.
> 
> If you're looking for more feedback beyond that - i.e. interface, execution, etc., let us know. : )

**Comment by susanBuck** [comment]
In the project description, I said:

> Data from your forms should be validated server-side using Laravel’s validation functionality to avoid unexpected output. To make it easy to check your server-side validation, HTML and JavaScript validation should not be used.

I'd categorize `type='number'` as a form of HTML validation because it will prevent me from entering a non-numerical value. Given that, it'd be my preference that you exclude it and just make it a regular text input so I can easily test your server-side validation. If you leave it in, I'll just use the web inspector to bypass it. : )

**Comment by anyav77** [comment]
> Hi @anyav77 -
> 
> If you're looking for feedback as whether this is a good fit for P2 - yup, it's perfect. Covers all the bases and nice that it has a real-world application.
> 
> If you're looking for more feedback beyond that - i.e. interface, execution, etc., let us know. : )

Thank you!

Here is the latest working version:
http://e15p2.atozez.com/

Work in progress: 
checkbox round-up calculation
dropdown - passing the selected field back to the page.

Please let me know if you have any comments or suggestions.
