### ISSUE TITLE
Class website sidebar nav, broken CSS

### ISSUE THREAD

**Issue by nicholsonjf** [susanBuck/e15-spring20#18]
Let me know if there is a better place to post feedback like this.

You can see in the red box in the attached screenshot that some CSS appears to be broken. My version of Chrome is in the window off to the side. I would have submitted a PR to try and fix it but I don't think the repo for the class site is public.

![sidebar-nav](https://user-images.githubusercontent.com/4286084/76125944-e1d42d00-5fcb-11ea-93ee-a33deabbe4cf.png)

**Comment by susanBuck** [comment]
Hi @nicholsonjf - Can you try clearing your browser cache and refreshing?

I made some tweaks to the menu's CSS. I have code present that should have forced your browser to re-cache the CSS, but I realize now I failed to add it to the Schedule page.

A manual cache refresh should do the trick though. : ) 

FYI - If anyone's curious - the slight redesign in the menu came as a result of [this discussion in my other course](https://github.com/susanBuck/e28-spring20/issues/20).

**Comment by nicholsonjf** [comment]
Hello @susanBuck, after a cache refresh the site looks as expected again 😎
![Screen Shot 2020-03-09 at 10 07 00 AM](https://user-images.githubusercontent.com/4286084/76220476-f263ed80-61ed-11ea-96ad-5f5e4405cd06.png)
