### ISSUE TITLE
Laravel-Blade syntax highlighting: correct theme required

### ISSUE THREAD

**Issue by nicholsonjf** [susanBuck/e15-spring20#19]
In order to achieve the same syntax highlighting on your .blade.php files as @susanBuck has in [Week 6 — Part 2: Views & Blade](https://www.youtube.com/embed/aWpPfxrNlLY?rel=0&showinfo=0) (i.e. the red blade directives seen starting at 21:00) you have to use the same color theme she recommends in week 1: luxcium.pop-n-lock-theme-vscode.

Hopefully this saves others any confusion. I had been using a different theme and it took me a while to figure out why my syntax highlighting didn't look the same as in the video.

![Screen Shot 2020-03-09 at 11 40 30 PM](https://user-images.githubusercontent.com/4286084/76277553-6d192100-625f-11ea-8b3b-451d2cd29ed8.png)

**Comment by susanBuck** [comment]
Hi @nicholsonjf - Thanks for pointing this out! It's true that themes will alter the colors used for syntax highlighting. The key thing is just that syntax highlighting *is* being applied (e.g. the blade syntax is not just all white). 

If it helps to see it exactly as I have it in my videos, using the same theme as me is the way to go. 👍

But, this isn't required - you can use different themes - you just need to get familiar with the color patterns that theme uses.

**Comment by nicholsonjf** [comment]
@susanBuck apologies for the confusing title! I will reiterate what Susan already pointed out: it is not a requirement to have a specific theme for Laravel-Blade syntax highlighting to work. Only if you want your syntax highlighting to match Susan's, do you need a specific theme (see original post).

**Comment by susanBuck** [comment]
@nicholsonjf - No problem! It's a good thing to note because I could see how some students might interpret it as "not working" if they see different colors. : )
