### ISSUE TITLE
if CSS changes aren't showing up, clear Chrome's cache

### ISSUE THREAD

**Issue by kreinholz** [susanBuck/e15-spring20#23]
This is a tip in case, like me, you've been playing around with your p2 CSS but Chrome isn't displaying those changes.

Go to Chrome > Settings > Privacy and security > Clear browsing data, and then check the box for "Cached images and files." Change the Time range as needed (in my case I just did "Last 24 hours.")

Hit "Clear data" and when you refresh your p2 page, your new CSS rules should be applied.

The reason why this happens is that certain files like your public CSS file gets stored in Chrome's browser cache in order to speed up your web browsing experience. Great for everyday Internet usage, but not so great for testing the look of CSS rule changes while developing a web app. Hope this helps!

**Comment by susanBuck** [comment]
Good tips! 

Piggy-backing on this, if you look in your browser's dev tools settings, there's an option to disable cache while the dev tools panel is open (screenshot below). This can be useful when doing CSS related development work.

Alternatively, there are keyboard shortcuts to do a "hard refresh" in the browser - that's a refresh plus a cache clear:

On Mac, it's `cmd` + `shift` + `R`
On Windows, it's `ctrl` + `shift` + `R`


![image](https://user-images.githubusercontent.com/237711/76788068-9faba800-6790-11ea-89f6-57a3d17cffa3.png)

**Comment by janenycxo** [comment]
> Good tips!
> 
> Piggy-backing on this, if you look in your browser's dev tools settings, there's an option to disable cache while the dev tools panel is open (screenshot below). This can be useful when doing CSS related development work.
> 
> Alternatively, there are keyboard shortcuts to do a "hard refresh" in the browser - that's a refresh plus a cache clear:
> 
> On Mac, it's `cmd` + `shift` + `R`
> On Windows, it's `ctrl` + `shift` + `R`
> 
> ![image](https://user-images.githubusercontent.com/237711/76788152-bfdb6700-6790-11ea-91a8-54d1adc1259f.png)

neat, i just tried this and it reflected my updated css styles!
