### ISSUE TITLE
Unable to get page to load

### ISSUE THREAD

**Issue by janenycxo** [susanBuck/e15-spring20#25]
Extension to previous apache not loading issue....
I followed the steps to get the production server back in running order -

**1. setting permissions for storage and bootstrap:**
 total 288
drwxr-xr-x 12 root     root   4096 Mar 19 18:47 .
drwxr-xr-x 10 root     root   4096 Mar 10 20:02 ..
-rw-r--r--  1 root     root    220 Mar 10 23:39 .editorconfig
-rw-r--r--  1 root     root    824 Mar 19 18:47 .env
-rw-r--r--  1 root     root    778 Mar 10 23:39 .env.example
-rw-r--r--  1 root     root    111 Mar 10 23:39 .gitattributes
-rw-r--r--  1 root     root    163 Mar 10 23:39 .gitignore
-rw-r--r--  1 root     root    174 Mar 10 23:39 .styleci.yml
-rw-r--r--  1 root     root    559 Mar 17 20:29 README.md
drwxr-xr-x  6 root     root   4096 Mar 10 23:39 app
-rw-r--r--  1 root     root   1686 Mar 10 23:39 artisan
drwxr-xr-x  3 www-data root   4096 Mar 10 23:39 bootstrap
-rw-r--r--  1 root     root   1503 Mar 10 23:39 composer.json
-rw-r--r--  1 root     root 180364 Mar 10 23:39 composer.lock
drwxr-xr-x  2 root     root   4096 Mar 10 23:39 config
drwxr-xr-x  5 root     root   4096 Mar 10 23:39 database
-rw-r--r--  1 root     root   2199 Mar 17 22:03 homePage.php
-rw-r--r--  1 root     root   1082 Mar 17 21:50 index.php
-rw-r--r--  1 root     root   1013 Mar 10 23:39 package.json
-rw-r--r--  1 root     root   1140 Mar 10 23:39 phpunit.xml
drwxr-xr-x  4 root     root   4096 Mar 17 21:35 public
drwxr-xr-x  6 root     root   4096 Mar 10 23:39 resources
drwxr-xr-x  2 root     root   4096 Mar 17 21:35 routes
-rw-r--r--  1 root     root    563 Mar 10 23:39 server.php
drwxr-xr-x  5 www-data root   4096 Mar 10 23:39 storage
drwxr-xr-x  4 root     root   4096 Mar 10 23:39 tests
drwxr-xr-x 25 root     root   4096 Mar 19 17:43 vendor
-rw-r--r--  1 root     root    538 Mar 10 23:39 webpack.mix.js

**2. verifying composer has been installed**
 / ____/___  ____ ___  ____  ____  ________  _____
 / /   / __ \/ __ `__ \/ __ \/ __ \/ ___/ _ \/ ___/
/ /___/ /_/ / / / / / / /_/ / /_/ (__  )  __/ /
\____/\____/_/ /_/ /_/ .___/\____/____/\___/_/
                    /_/
Composer version 1.10.1 2020-03-13 20:34:27

**3. php extension updated**
**4. verified vendor and .env directory are present
5. generated the app key and switched back to localhost
6. subdomain settings are set to /var/www/html/e15/p2/public
7. Trying to avoid complicating matter, I corrected routes/web.php to point to** 

//Home
Route::get('/', 'HomeController@index');

//BMI Calculator
Route::get('/bmi', 'BmiController@index');
Route::get('/bmi/{title?}', 'BmiController@show');

and when loading http://e15p2.janenycxo.me I receive this error:
Target class [App\Http\Controllers\homePage] does not exist.

The route is no longer pointing the to homePage (which i renamed HomeController) and I checked namespace (and left at default without making any changes) on Controller.php.

**8. MySql fails to start**

**9. and the page no longer fails to open locally either**

Sorry I have made a bigger mess, I wanted to share, and will continue to work on resolving. TIA!! Jane

**Comment by janenycxo** [comment]
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}
 
**8. MySql fails to start
9. and the page no longer fails to open locally either**

Sorry I have made a bigger mess, I wanted to share, and will continue to work on resolving. TIA!! Jane

**Comment by janenycxo** [comment]
**8. MySql fails to start
9. and the page no longer fails to open locally either**

Sorry I have made a bigger mess, I wanted to share, and will continue to work on resolving. TIA!! Jane

**Comment by RGPhD** [comment]
@janenycxo 
Stackoverflow has this solution <https://stackoverflow.com/questions/37975921/class-app-http-controllers-postcontroller-does-not-exist>
and Laracasts also shows just a typo fixed the error <https://laracasts.com/discuss/channels/laravel/target-class-apphttpcontrollerseventscontroller-does-not-exist>.

¯\_(ツ)_/¯

Robelyn

**Comment by susanBuck** [comment]
FYI Cloning locally now to test. Will follow-up with what I find. 👍

**Comment by susanBuck** [comment]
## Debugging local
When I tested your project locally, I received an error:

```
View [index] not found
```

[Full error output here...](https://flareapp.io/share/v5pWED7E#F45)

This is triggered from the `HomeController` which is attempting to load a view called `index`:

```php
public function index()
{
    return view('index');
}
```

But no such view exists. Looking at your views directory, I do see a `welcome.blade.php` view file, so I renamed that to `index.blade.php` and was able to load the site:

![image](https://user-images.githubusercontent.com/237711/77178762-edc8f000-6a9d-11ea-8992-474b7c3e33bb.png)

## Debugging production
When I load your site on production (http://e15p2.janenycxo.me/) it produces a different error - the one you reported:

```
Target class [App\Http\Controllers\homePage] does not exist.
```

The different errors on local vs. production indicates to me that the code bases are not insync.

To verify, I ran `git status` on production and saw there were two changes there:

![image](https://user-images.githubusercontent.com/237711/77179078-5f08a300-6a9e-11ea-8454-1f7332752d33.png)

We really want to avoid editing code files directly on production. It can be tempting, especially when you just want to test a quick fix : ) But it often leads to bigger problems down the road in regards to the code bases becoming out of sync, merge conflicts, etc.

To get production back in sync, I wanted to do a "hard reset" which would disregard any changes on production, bringing it back in sync with what is in Github. Before I did this, I backed up the files shown in the above git status just in case you don't have that code stored elsewhere.

Then I did the hard reset with these commands:
```
git fetch --all; git reset --hard origin/master
```

Once that was done, production was now showing the same error about `index` view not being found, confirming it was back in sync with local/Github:

![image](https://user-images.githubusercontent.com/237711/77179513-f53cc900-6a9e-11ea-99e6-31bca7aa1189.png)

So if you address the bug locally, sync the changes with Github and then production, it should be good to go.

**Comment by janenycxo** [comment]
Thank you Susan! I really benefit from your troubleshooting, especially the steps you outline. 

Although I haven't checked with the project today (...aside from accepting a ghost town in the city that never sleeps, my lovely home city reached an exponential amount of people affected by covid-19, Gov. Cuomo issued a state of shut down in NYC earlier today. Plus managing 5 kids at home which includes having to arrange work space, we have also been picking up school assignments and setting up the technology for them to sign onto online learning.) Everything is happening so quickly and yet I feel robotic...the supermarkets here are picked clean. We are required to make preparations for 2 week home bound which will be enforced. Never in my life has school shut down for a month with no plans to reopen. Events and graduation ceremony have also been postponed...with no further instruction as to when it will return to normal.

I find assurance with HES because we are entirely online, somethings remain the same. I am confident with your continued guidance there will be more quality learning.  Also @RGPhD....you rock!! I love all your feedback! Thank you both!

**Comment by janenycxo** [comment]
Finally got it to work...lots of troubleshooting but always so rewarding to figure it out. The p2 works BUT i have to configure the formula. Every entry shoots back in the "normal' range even when the fields I enter obviously outrageous numbers (i.e. female, 2 feet 0 inches, 500 pounds). Closing because its a form function and no longer a production issue.  Thank you again!

**Comment by susanBuck** [comment]
@janenycxo Can't imagine how tough life in NYC is right now. This is a really bizarre time.

Kudos to you for sticking with it and solving the problem, all while balancing everything you have on your plate! 

Keep the questions coming as you run into road blocks - you don't have to do this alone. : )

**Comment by RGPhD** [comment]
@janenycxo @susanBuck  😊 😷
