### ISSUE TITLE
Bookmarks application - nav and book covers don't load

### ISSUE THREAD

**Issue by anyav77** [susanBuck/e15-spring20#26]
I'm trying to bring the Bookmarks application in synch with Week 7 video, but I'm getting some errors.

1. nav doesn't load
2. book covers and links don't load, but the titles load ok
3. The individual book pages return database error

Latest commit with the updated code:
https://github.com/anyav77/e15/commit/c8fb649267313431b58d4936b5246ce4de6eb1a8

> Facade\Ignition\Exceptions\ViewException
Undefined variable: title (View: C:\xampp\htdocs\e15\bookmark\resources\views\books\show.blade.php)
![books and nav not loading](https://user-images.githubusercontent.com/1045307/77244567-58c81300-6bd3-11ea-99e5-f94b18ecec17.png)
![page error](https://user-images.githubusercontent.com/1045307/77244576-7bf2c280-6bd3-11ea-9c33-b6152120f595.png)

**Comment by anyav77** [comment]
It seems to be a caching issue... I added some text and dd statements and refreshed the pages, and that helped.

Perhaps, it happened because I copied the files directly to the xampp folder without using text editor?

**Comment by susanBuck** [comment]
That's odd - there shouldn't be any sort of server-side code caching in our current setups. Not quite sure what happened here, but glad it's resolved! : )

**Comment by smsummers1** [comment]
I am also getting an issue with a book cover not displaying on my /books page.

Correctly displaying:
[https://hes-bookmark.s3.amazonaws.com/harry-potter-and-the-chamber-of-secrets.jpg](https://hes-bookmark.s3.amazonaws.com/harry-potter-and-the-chamber-of-secrets.jpg)

Not displaying:
[https://hes-bookmark.s3.amazonaws.com/harry-pottern-and-the-philosophers-stone.jpg](https://hes-bookmark.s3.amazonaws.com/harry-pottern-and-the-philosophers-stone.jpg)

The cover that is not displaying is giving the following error when I visit the link:

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>harry-pottern-and-the-philosophers-stone.jpg</Key>
<RequestId>5F287D439BBF1AC3</RequestId>
<HostId>
LXQETPiIbAaJfTZfc8leux+ty4sh3hFpyFKKiP4xoOVfHIYg3wHOPcYDTCeqFGatz09feJ7uGFg=
</HostId>
</Error>
```

**Comment by susanBuck** [comment]
Hi @smsummers1 - 

I had a typo in the original url for the philosopher's stone book.

What is: `https://hes-bookmark.s3.amazonaws.com/harry-pottern-and-the-philosophers-stone.jpg` (extra `n` after potter)
Should be: `https://hes-bookmark.s3.amazonaws.com/harry-pottern-and-the-philosophers-stone.jpg`

Fix this in your `books.json` seed data and the image should load. 👍

**Comment by smsummers1** [comment]
That fixed it.  I can't believe I didn't spot that myself.  Thanks.
