### ISSUE TITLE
Best Storage for Image Data

### ISSUE THREAD

**Issue by budostylz** [susanBuck/e15-spring20#28]
Need to get my head around this. I want to know what is the best optimal location to store image data. I’m researching MySQL, Redis and AWS. Want to get a better glimpse on what locations are the most optimal.

**Comment by susanBuck** [comment]
Are you thinking basic site assets (logo, graphics, etc.) or images users might upload (e.g. it'd be a growing library of images)?

For a simple, low traffic site, hosting the images directly on your own server is sufficient.

For more robust sites, I usually host images via Amazon S3.

I would not reccommend storing image data directly in a MySQL database. It's possible, but not the optimal way to handle image/file data.

**Comment by budostylz** [comment]
Yes, I’m looking into the scenario where users can upload images. This storage will be growing over time. I’ll take your lead of investigating Amazon S3. Thank you for the feedback Susan.

**Comment by susanBuck** [comment]
Cool - Amazon S3 (or something equivalent) is a great solution in that scenario.

You can also do a lot in terms of interacting with S3 from your application.

Two external packages I often use in projects to help with this include [aws/aws-sdk-php](https://github.com/aws/aws-sdk-php) and [aws/aws-sdk-php-laravel](https://github.com/aws/aws-sdk-php-laravel).

**Comment by budostylz** [comment]
Sweet, I’m going to check these out and work on spinning this up for project 3. Very cool, thanks again Susan.

**Comment by budostylz** [comment]
This class is serious. Now I can put AWS on my resume. Lol!!
