### ISSUE TITLE
Security alerts when pushing code to Github (symfony/http-foundation)

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e15-spring20#29]
While recording one of this week's lecture videos (*[Week 9, Part 7: Prod. database config](https://www.youtube.com/embed/n8Cw7-emGW0?rel=0&showinfo=0)*), I was going through the process of pushing the latest changes to my `e15` repository to Github and ran into this this notice:

```
remote: Resolving deltas: 100% (9/9), completed with 9 local objects.
remote: 
remote: GitHub found 1 vulnerability on susanBuck/e15's default branch (1 low). To find out more, visit:
remote:      https://github.com/susanBuck/e15/network/alerts
remote: 
```

Following the URL of `https://github.com/susanBuck/e15/network/alerts` lead me to a page letting me know that there was a minor security issue related to the dependency `symfony/http-foundation` and the solution was to update the dependency in my project.

This is not a dependency we directly include in our projects, but it's used in our project as one of Laravel's dependencies.

My first steps in addressing this project was to run `composer update` locally, as I suspected that there might be a patch update in Laravel to address this very issue.

This ended up to be true and I saw that Laravel had patch update:
```
Updating laravel/framework (v6.18.2 => v6.18.3): Downloading (100%)     
```

And as a result of that, so did `symfony/http-foundation`:
```
Updating symfony/http-foundation (v4.4.5 => v4.4.7): Downloading (100%)   
```

So with that update, the problem was resolved.

A couple takeaways from this example:

1. Github.com will scan your dependencies, alerting you of vulnerabilities. (It won't catch every vulnerability - just the ones that have been reported to Github)
2. Version 6 of Laravel is considered a LTS (Long Term Support) version, which means that even though it's not the most current version of Laravel (7), it will continue to receive minor updates to address bugs and security issues, as we saw in this example. To learn more about this, read their [Support Policy...](https://laravel.com/docs/7.x/releases#support-policy)

Note: All of the above information is covered in the video where I ran into this issue, but I just wanted to document it here in case anyone ran into it before getting to that video.

**Comment by smsummers1** [comment]
I didn't have that Security Alert come up for me when I ran `composer update` on the bookmark app.  I think it was because I updated the bookmark app to Laravel 7.  

But I did get the following warning....

`Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.`

Not sure how to fix this issue.  Any resources you could send my way would be great.  Thanks.

**Comment by susanBuck** [comment]
> I did switch over to Laravel 7 on the bookmark project.

Agree that's the reason you didn't get the error. L7 had probably already updated `symfony/http-foundation` by the time you set it up.

**Re: the notes on abandoned packages -**

If you run `composer show --tree` within your project you can see a tree list of dependencies for that project.

Using this info, we can track which parent packages are including the abandoned packages.

In this case, it looks like `jakub-onderka/php-console-color` and `php-console-highlighter` are children of `laravel/tinker`:

![image](https://user-images.githubusercontent.com/237711/78514518-c6ea0980-777f-11ea-9521-e288fbb1bb86.png)

When facing an abandoned package from one of your "inherited" dependencies, you have a few options:

+ Wait for `laravel/tinker` to update addressing the abandoned packages. 
+ Submit a pull request to `laravel/tinker` with a request to swap the abandoned packages for the suggested one.
+ If the pull request isn't accepted, you can fork `laravel/tinker` to your own copy where you could address the packages. Downside of this is then you'd be out of sync with future updates of `laravel/tinker`

[Laravel Tinker](https://laravel.com/docs/7.x/artisan#tinker) is a command line program that lets you run code within the context of your application. It's not mission critical; just useful if you ever want to test out a few commands on the fly without having to run it from your files. 

Because it's not essential we have access to it on production, we could move it from `require` to `require-dev` so that it will only ever be installed locally. This way, if there is a security flaw that pops up in those abandoned packages, it wouldn't be able to do any harm on your production server.

In the context we're working in, I wouldn't worry about it. In a real world application with any sensitive information, I'd be more cautious and do more research on whether there's any concern with the abandoned packages.
