### ISSUE TITLE
Helpful Plugins and Tools

### ISSUE THREAD

**Issue by RGPhD** [susanBuck/e15-spring20#3]
Hello Professor @susanBuck,

In video Week 1: Part 2, you mention the Chrome plugin *Full Page Screen Capture*, this is very helpful.  I was also curious what plugin you utilize for pausing your videos following the recordings to add comments.  I remember you using it in E-2 and you use it in our **E-15 video Week 1: Part 4: time 5:06**; this tool seems very useful.

Thank you kindly,
Robelyn

**Comment by susanBuck** [comment]
Hi @RGPhD - I record/edit the screencasts using [ScreenFlow](https://www.telestream.net/screenflow/).

The pause effect is just something I add in editing via a pause button graphic + sound effect. : )

**Comment by RGPhD** [comment]
Thank you!
