### ISSUE TITLE
Broken link on https://hesweb.dev/e15/week/9

### ISSUE THREAD

**Issue by kreinholz** [susanBuck/e15-spring20#31]
On https://hesweb.dev/e15/week/9, there is a broken link to "Seeders" under **Laravel & Databases cont’d**.

However, the left navigation pane link within https://hesweb.dev/e15/notes works just fine.

The missing "Seeders" notes link is:

https://hesweb.dev/e15/notes/laravel/db-seeders

**Comment by susanBuck** [comment]
Thanks; just fixed!
