### ISSUE TITLE
books table contains no data after running seeders

### ISSUE THREAD

**Issue by janenycxo** [susanBuck/e15-spring20#35]
The book list is empty on phpMyAdmin despite entering in the seeders multiple times. When I check the phpMyAdmin database after running practice queries I receive an error message as shown in the attachment. 
[phpMyAdmin Error.docx](https://github.com/susanBuck/e15-spring20/files/4452488/phpMyAdmin.Error.docx)

Here is a link to my latest updates-
https://github.com/janenycxo/e15/tree/master/bookmark

thanks for helping me sort this out!
J

**Comment by susanBuck** [comment]
Hi @janenycxo - I believe the problem is your master seed file `DatabaseSeeder.php` is not invoking your `BooksTableSeeder`.

Check out these notes for reference: https://hesweb.dev/e15/notes/laravel/db-seeders#master-seeder

**Comment by janenycxo** [comment]
Commenting out the UsersTableSeeder and adding BooksTableSeeder (DatabaseSeeder.php) then re-entering the SQL (phpMyAdmin) resolved the error.
Thank you!

![image](https://user-images.githubusercontent.com/55065945/78843558-1ecb7f00-79d1-11ea-8a07-842712aa5ca8.png)
