### ISSUE TITLE
Project 3 JavaScript Usage

### ISSUE THREAD

**Issue by budostylz** [susanBuck/e15-spring20#36]
I plan on using Laravel Mix for my css front-end assets. Laravel Mix uses node.js ecosystem to handle the builds. Will it be possible to use JavaScript in this respect for project 3? 

V/r, Shaun

**Comment by susanBuck** [comment]
Hi @budostylz - Yup, you can use Laravel Mix to compile CSS front-end assets.

**Comment by budostylz** [comment]
Awesome, why did I have a slight feeling that you were going to say yes? Thanks a bunch.

V/r,
Shaun
