### ISSUE TITLE
MySQL Timestamp Data Type

### ISSUE THREAD

**Issue by budostylz** [susanBuck/e15-spring20#37]
According to the documentation at [tutorialspoint](https://www.tutorialspoint.com/mysql/mysql-data-types.htm) a timestamp field have the following constraint:
`A timestamp between midnight, January 1st, 1970 and sometime in 2037.`

The official [MySQL](https://dev.mysql.com/doc/refman/5.7/en/datetime.html) documentation defines timestamp as:

`The TIMESTAMP data type is used for values that contain both date and time parts. TIMESTAMP has a range of '1970-01-01 00:00:01' UTC to '2038-01-19 03:14:07' UTC.`

What will happen after 2037? Will there be a similar situation like the y2k scare or will the field be automatically adjusted for the current date/time? I'm assuming the later.

**Comment by susanBuck** [comment]
This is often referred to as the "Year 2038 problem" 

Fantastic details about this problem here: 
https://stackoverflow.com/a/2012620/59479

**Comment by cjreilly** [comment]
Hi @budostylz,
Your question is very relevant to much more than just the MySQL timestamp. It is a fairly safe bet to assume the MySQL teams will solve the problem without any impact on your application. That is what they do, after all. These problems around future-proofing traditional models that are known to expire on a given date have been around long before the Mayan calendar. What isn't already automated in IT is likely to already be reduced to a series of routine manual steps.
Sometimes it's helpful to think about these things as models of real-world events. If you can't model your data with the TIMESTAMP type (i.e. it does not fall within the range) then you may need a different data type. But if you can afford your own MySQL team, I'm sure they can build and maintain several data types to do just what you want. ;-)
If you are still very concerned about things expiring then MySQL has the option to develop TRIGGER functions, EVENT functions, and stored procedures.

**Comment by budostylz** [comment]
Thank you for the insight @cjreilly. I really appreciate your feedback.
