### ISSUE TITLE
migrations and one-to-many relationships

### ISSUE THREAD

**Issue by kreinholz** [susanBuck/e15-spring20#38]
I thought about holding off in case we cover this in Week 11, but I'm pulling my hair out with database migrations when one-to-many relationships (and foreign keys in general) are involved.

What I'm trying to do, is create a table for "checklist items" like one would see on an inspection checklist. I then want a second table for "checklists" which can contain any number of "checklist items." Finally, I want an "inspections" table where the inspector, a foreign key from the Users table, can select a checklist and basically fill it out and save the results to the database.

I set my "checklists" migration file up like so:

```php
    public function up()
    {
        Schema::create('checklists', function (Blueprint $table) {
            # Auto-incrementing UNSIGNED BIGINT (primary key) equivalent column
            $table->bigIncrements('id');

            # Adds nullable created_at and updated_at TIMESTAMP equivalent columns with precision (total digits)
            $table->timestamps();

            # Add a title for this particular checklist, e.g. "Checklist for Reviewing the Rail Transit Agency Safety Plan"
            $table->string('title');
        });
    }
```

And my checklist items migration file like so:

```php
public function up()
    {
        Schema::create('checklist_items', function (Blueprint $table) {
            # Auto-incrementing UNSIGNED BIGINT (primary key) equivalent column
            $table->bigIncrements('id');

            # Checklist Item Number TINYINT
            $table->tinyInteger('item_number');

            # Checklist Item Name VARCHAR
            $table->string('item_name');

            # Checklist Item Included BOOLEAN
            $table->boolean('included');

            # Checklist Item Page Reference SMALLINT
            $table->smallInteger('page_reference');

            # Checklist Item Comments TEXT
            $table->text('comments');

            # Add foreign key associating checklist items with a checklist
            # Ref: https://www.itsolutionstuff.com/post/laravel-one-to-many-eloquent-relationship-tutorialexample.html
            $table->foreign('checklist_id')->references('id')->on('checklists')->onDelete('cascade');
        });
    }
```

I also edited the Checklist model to include a "hasMany" constraint:

```php
class Checklist extends Model
{
    # Allow a Checklist to contain MANY Checklist Items
    # Ref: https://www.itsolutionstuff.com/post/laravel-one-to-many-eloquent-relationship-tutorialexample.html
    public function checklist_items()
    {
        return $this->hasMany(ChecklistItem::class);
    }
}
```

And the ChecklistItem model as well:

```php
class ChecklistItem extends Model
{
    # Allow MANY Checklist Items to belong to a Checklist
    # Ref: https://www.itsolutionstuff.com/post/laravel-one-to-many-eloquent-relationship-tutorialexample.html
    public function checklists()
    {
        return $this->belongsTo(Checklist::class);
    }
}
```

This setup fails **php artisan migrate** with the following error message:

```
  SQLSTATE[42000]: Syntax error or access violation: 1072 Key column 'checklist_id' doesn't exist in table (SQL: alter table `checklist_items` add constraint `checklist_items_checklist_id_foreign` foreign key (`checklist_id`) references `checklists` (`id`) on delete cascade)
```

To say nothing of my "inspections" migration failing because of a similar complaint about "users" ("id") not existing...which makes no sense to me since the Users table exists by default...

Here's my [p3 repository](https://github.com/kreinholz/e15/tree/master/p3).

Again, if I'm getting ahead of myself, I can wait, it's just that figuring out whether this database structure is even workable is kind of crucial to the development of p3, since my idea is to let the main user create and edit checklist items and build checklists, and other users to be able to create/edit inspections that utilize checklists containing checklist items. (And of course to view the inspections with all checklist items answered).

I'm pretty sure although I'm obviously missing something, this is possible, as I set up some fairly gnarly foreign key and many-to-many relationships in a Django project that used a SQL database a year ago. Relationships between tables wouldn't even be an issue in a NoSQL database like MongoDB, which I've also worked with.

Anything jumping out that I'm missing? I suspect it's something relatively simple...but then again I could've set this up completely wrong.

**Comment by budostylz** [comment]
The problem looks like it's within your check_list items migration file where you are referencing the foreign key. You might have to instantiate the checklist_id column first before referencing it as a foreign key. 

I understand that there are three entities you are working with, checklist items, checklists and inspections. I'm a bit curious of the first two entities, checklist items and checklist. To me this would seem like one table, checklist with checklist items as rows or go 3D with a  JSON column within those checklist items. The JSON option is a matter of how you want to scale since it has a bit of a  limit. 

The inspector's table have the foreign key from the Users table which makes sense since the users table act as kind of like the authentication table.

**Comment by susanBuck** [comment]
@budostylz is correct:

> You might have to instantiate the checklist_id column first, then reference it as a foreign key.

Example:
```
# First initialize a new column to act as the foreign key (note: all FKs must be defined as unsigned)
$table->bigInteger('checklist')->unsigned();

# *Then* define that column as a foreign key
$table->foreign('checklist')->references('id')->on('checklists');
```

In my clone of your p3, when I initialized all the FK columns first, I was able to get the migrations to run without error:

```
~/Sites/hes/dwa-bash/students/kevin/e15/p3 (master) ! $ pa migrate:fresh
Dropped all tables successfully.
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table (0.02 seconds)
Migrating: 2019_08_19_000000_create_failed_jobs_table
Migrated:  2019_08_19_000000_create_failed_jobs_table (0.01 seconds)
Migrating: 2020_04_11_192808_create_checklists_table
Migrated:  2020_04_11_192808_create_checklists_table (0.01 seconds)
Migrating: 2020_04_11_194010_create_checklist_items_table
Migrated:  2020_04_11_194010_create_checklist_items_table (0.04 seconds)
Migrating: 2020_04_11_196012_create_inspections_table
Migrated:  2020_04_11_196012_create_inspections_table (0.06 seconds)
```

**Comment by kreinholz** [comment]
Thank you @budostylz and @susanBuck! Migrations now completed successfully!

@budostylz, you're absolutely right about the checklist and the checklist items seeming like one table, since a checklist is composed of checklist items, and if I were using MongoDB (syntactically, for all intents and purposes, JSON), I'd embed an array inside of my checklist object that contained checklist item objects. But, I think with relational databases, separating out the tables makes sense, as in the future a lead inspector could create a new checklist that incorporates some but not all of the existing checklist items, or adds new ones. So splitting them into separate tables provides more flexibility/future-proofing.

I suspect I still have some work to do on my inspections table--I don't want the checklist items to be modified in their original table when an inspector creates/edits a new inspection. I want them copied over, so the inspector can then fill in the details. Essentially, I visualize inspections and checklists as 2 separate "databases," or using the NoSQL analogy, separate JSON objects. I want to _copy_ the checklist items from a selected checklist into an inspection, where edits to them won't impact the original checklist items. Some Googling has suggested this might be possible using the `replicate()` method.

Maybe I'm going overboard on the database side of p3, but this is something I really want to nail down, because setting this set up the way I envision would allow for future customization of the checklists/inspections by users without any knowledge of SQL. Their needs could all be met from the web app interface.

Thanks again for helping me troubleshoot my migrations! If I get stuck on the `replicate()` issue, I may post again. :) And, I'm about to go through the Week 11 material so that may preemptively answer any future questions on this subject.
