### ISSUE TITLE
Eager loading - many to many relationships

### ISSUE THREAD

**Issue by nnoel2626** [susanBuck/e15-spring20#39]
I am using belongsTomay relationship in my P3 project. Is it possible to eager load in a belongsToMany relationship? If yes, how do you accomplish it? 
Thanks.

**Comment by RGPhD** [comment]
@nnoel2626,
The only way I can see to use this is with the pivot model.  I have not got that point in my P3 yet, so not sure how to accomplish it.
Good luck,
Robelyn

**Comment by nnoel2626** [comment]
thx

**Comment by susanBuck** [comment]
It is possible, and works similar to eager loading with a one-to-many relationship. 

Here's an example we'll see in the upcoming Week 12's lectures:

```php
# Eager load users to reduce number of queries
$books = Book::with('users')->get();

foreach ($books as $book) {
    if ($book->users->count() == 0) {
        dump($book->title . ' is not on any user’s list');
    } else {
        dump($book->title . ' is on the following user’s lists:');

        foreach ($book->users as $user) {
            dump($user->email);
        }
    }
}
```

In this example, the User model has a `books` relationship method:

```php
public function books()
{
        return $this->belongsToMany('App\Book')
            ->withTimestamps()
            ->withPivot('notes');
}
```

And likewise, the Book user model has a `users` relationship method:

```php
public function users()
{
        return $this->belongsToMany('App\User')
             ->withTimestamps() # must be added to have Eloquent update the created_at/updated_at columns in a pibot table
             ->withPivot('notes'); # Must also specify any other fields that should be included when fetching this relationship
}
```
