### ISSUE TITLE
Week 1 assignment "Some questions are not yet graded"

### ISSUE THREAD

**Issue by nicholsonjf** [susanBuck/e15-spring20#4]
## Description
After submitting the quiz I received my score and saw a message that said `some questions are not yet graded` (see attached screenshot).

Does this mean any points from those questions will be added to the total once they are graded? I didn't see anything about this in the notes but it's possible I missed something.

## Screenshot
<img width="661" alt="not-yet-graded" src="https://user-images.githubusercontent.com/4286084/73710364-c1196e80-46d1-11ea-8b0c-4b55dba46719.png">

**Comment by susanBuck** [comment]
That’s correct - once I grade the open-ended questions, you’ll be able to see the final grade.

FYI I shoot to complete weekly assignment grades  within 7 days of the cutoff for submission. When I release grades you should get a notification from Canvas at which point you’ll be able to go in and see your grade, what questions you missed/got correct, and any comments I may have made.

**Comment by nnoel2626** [comment]
That makes sense now. I kept retaking the quiz thinking it was me that didn't answer some of the questions correctly. I get it now.
