### ISSUE TITLE
Request for Week 13 - HTTPS

### ISSUE THREAD

**Issue by kreinholz** [susanBuck/e15-spring20#40]
@susanBuck,

I have a request that might fall under "TBD" for Week 13 content. Since this week covered users and authentication, would it be possible to do even a short video on using HTTPS with Laravel?

There's a [short section on encryption in the Laravel documentation](https://laravel.com/docs/7.x/encryption), but I don't feel like this really covers everything we need to know re HTTPS.

Especially now that we have user authentication, it seems like HTTPS would be a really helpful change to make to our projects, even if it's not a p3 requirement. (I certainly wouldn't want users transmitting registration or login information unencrypted).

If you've already selected other content for Week 13, or others wouldn't find this topic helpful or interesting, that's OK, but I thought it would make a logical companion to Week 11's videos on authentication (Parts 2 & 3). It's certainly a topic I intend to explore on my own once the course is finished if we aren't able to get to it this semester.

**Comment by susanBuck** [comment]
Sure thing @kreinholz! I agree HTTPS/SSL is an important topic and fits well with our studies.
