### ISSUE TITLE
Having trouble with Production Server

### ISSUE THREAD

**Issue by budostylz** [susanBuck/e15-spring20#42]
I'm having trouble accessing my p3 at the below url. 

http://e15p3.budoapps.com/

Trying to troubleshoot to see what is going on. I installed phpRedis in my droplet. I want to use Redis as a cache for p3. Not sure if that is a factor.

**Comment by budostylz** [comment]
I figured it out. I did not perform the preq steps to deploy a Laravel app on production. I was going a bit too fast. lol!

**Comment by budostylz** [comment]
Successfully configured Redis on both local and production servers. Whooooooh! I want to use Redis as an intermediary between the client and MySql for project 3.

**Comment by susanBuck** [comment]
Glad you got it all sorted out. : )
