### ISSUE TITLE
Help with Eloquent query.

### ISSUE THREAD

**Issue by nnoel2626** [susanBuck/e15-spring20#43]
I have two tables with the following relationship. Location Model hasMany microphones and  Microphone Model belongsTo  location.
The microphones table has the location_id foreign key for the location tables.
The locations table has the following fields: building, room, city, state, postal_code.
I am doing a search query on the Microphone Model  by searchTerms ( Example building or room), and searchType (selecting the corresponding searchtype) of the two fields that are in the locations table.
My question is, is there an efficient way to pull relevant fields information from the location table in the search.
Any help will be appreciated!

**Comment by nnoel2626** [comment]
I solved the problem. Thx.
```
 $microphones  = Microphone::where ('band','LIKE', '%'.$searchTerms.'%')
             ->orwhereHas('location', function ($q) use ($searchTerms, $searchType){
                    $q->where('building', 'like', '%'.$searchTerms.'%')
                      ->orWhere('room', 'like', '%'.$searchTerms.'%');
             })->get();
```

**Comment by susanBuck** [comment]
Great solution, @nnoel2626. : )
