### ISSUE TITLE
I ran composer install --no-dev on the local server

### ISSUE THREAD

**Issue by anyav77** [susanBuck/e15-spring20#44]
I ran composer install --no-dev on the local server by mistake.  Should I revert anything?

**Comment by susanBuck** [comment]
Nope, it won't cause any problems. It would just do the updating of your dependencies by referencing `composer.lock` instead of `composer.json`.

You can just re-run as `composer update --no-dev` and you'll be back on track.

**Comment by anyav77** [comment]
Thank you!  I did.
