### ISSUE TITLE
Database design question - notes column in books table instead of pivot table?

### ISSUE THREAD

**Issue by nnoel2626** [susanBuck/e15-spring20#46]
Why couldn't you add the 'notes' column in the books table instead of having it in the pivot table?
What is the main difference?
Thanks.

**Comment by susanBuck** [comment]
We want each user to have the option of storing their own notes for a corresponding book.

If the `notes` field was part of the books table, this would not be possible.

Does that make sense?

**Comment by nnoel2626** [comment]
Thanks for the clarification.

**Comment by RGPhD** [comment]
Dear Professor @susanBuck,
Does this mean only logged in users Jill/Jamal can store ```notes```?
Robelyn

**Comment by susanBuck** [comment]
Hi @RGPhD - Jill, Jamal, or any registered and logged in user can record notes.

**Comment by RGPhD** [comment]
Thank you @susanBuck
