### ISSUE TITLE
Authentication setup on production question

### ISSUE THREAD

**Issue by RGPhD** [susanBuck/e15-spring20#47]
Dear Professor @susanBuck,

After pulling the **authentication setup code changes from Week 11 and pivot table changes from Week 12 to production**, will we have a separate set-up procedure for ```auth``` on production next week?

Thank you,

Robelyn

**Comment by susanBuck** [comment]
Hi @RGPhD - Apologies for the delay in response to this thread - I missed it in my inbox on Friday. : )

There shouldn't be any changes to our usual deploy process on production with the introduction on auth.

You will need to run migrations on production again, though, as we've introduced new tables.

I'll show that in this week's lectures just to be clear/as a reminder.

**Comment by RGPhD** [comment]
Thank you @susanBuck
