### ISSUE TITLE
Google Maps Usage(JavaScript API)

### ISSUE THREAD

**Issue by budostylz** [susanBuck/e15-spring20#48]
Hello Susan, will it be ok to use Google Maps JavaScript API to pull business listings? I understand the restricted usage of JavaScript for project 3 but I will just use JavaScript to pull the listings from Google and process those inputs in Laravel. I notice one of the previous projects(Gift Guru) was pulling data from Amazon.

V/r,
Shaun

**Comment by susanBuck** [comment]
Yup, that's fine!

**Comment by budostylz** [comment]
Awesome, thank you Susan.
