### ISSUE TITLE
dusk tests require full path on Windows?

### ISSUE THREAD

**Issue by kreinholz** [susanBuck/e15-spring20#49]
On my Windows 10 machine, I came across an odd issue when attempting to run dusk tests.

I ran the tests using the command `php artisan dusk` from within my `e15/bookmark` directory, but all tests failed, and viewing the screenshots revealed why: headless Chrome was resolving `'/'` as `http://localhost` and therefore not visiting the Bookmark application at all.

I was able to get the tests to run and to report success by specifying the full path I wanted dusk to visit, e.g.:

```php
->visit('http://e15bookmark.loc/login')
```

instead of 

```php
->visit('/login')
``` 

That having been said, I wonder why this was necessary. Perhaps it's a Windows-ism, or perhaps I missed a step when installing dusk, but it's strange behavior and undesirable because it makes my tests more fragile--I'd much prefer to use relative paths!

Anyone else come across this issue, whether using Windows or not?

**Comment by susanBuck** [comment]
Hi @kreinholz -

Odd - I ran the same Bookmark tests on my Windows 10 machine and they succeeded. 

Can you check your `APP_URL` in `.env` and confirm it's set to `http://e15bookmark.loc` (vs. the default which is `http://localhost`)?

**Comment by kreinholz** [comment]
@susanBuck, that was it! I feel silly, but sure enough that was the problem! Easy fix...thank you!
