### ISSUE TITLE
ANNOUNCEMENT: Change to weekly assignment grading configuration

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e15-spring20#5]
Hi everyone,

I'm writing to announce a change in how weekly assignments are configured (starting in Week 2).

In past semesters, I had it configured so you could submit an assignment multiple times but it was always your *latest* submission that was the recorded grade. This allowed students the opportunity to preview an assignment early in the week.

This configuration was occasionally problematic because students would sometimes accidentally open the assignment after they had made their "final" attempt, and it triggered a new submission they did not intend to make.

I thought the best way around this was to configure the assignments so that your *highest* score was the one that was recorded. That way, if you inadvertently opened the assignment, you could submit it with no answers, knowing the 0 score would be disregarded.

What I naively failed to think about is how students could game this configuration - if a student is unsure of an answer to a question, they could just submit the assignment multiple times with each potential answer selected, and then let the highest scoring assignment "win." This technique might boost one's grade, but it hinders my ability to see what concepts students are struggling with and assign grades that honestly reflect each student's performance/understanding. 

**Because of this, starting with the Week 2 assignment and moving forward, it will always be your *latest* attempt that will be recorded. You will still be allowed to make multiple attempts so that you can review the assignment early in the week.** 

-Susan

**Comment by janenycxo** [comment]
Thanks Susan for clarifying. Tip: print the quizzes so you have a hard copy to work on.

**Comment by budostylz** [comment]
Thanks for the update Susan.
