### ISSUE TITLE
Setting up Laravel on AWS EC2

### ISSUE THREAD

**Issue by anyav77** [susanBuck/e15-spring20#52]
I'm trying to set up a test instance of Laravel on AWS for the independent study.

I'm following these tutorials:
https://www.clickittech.com/aws/amazon-ec2/deploy-laravel-on-aws-ec2/
https://www.clickittech.com/aws/create-amazon-ec2-instance/

Amazon has updated its interface, so it looks different from the screenshots.  
So far, I was able to create an Ubuntu Server and launch EC2 instance.  In theory, I'm on step 18 of this tutorial:
https://www.clickittech.com/aws/create-amazon-ec2-instance/

I tried entering the public IP or public DNS in the browser, and I get "This site can’t be reached" error.
Is it because I haven't finished the setup yet?

**Comment by susanBuck** [comment]
Hi @anyav77 - I don't have recent experience with deploying Laravel to EC2 so I'm afraid I don't have an immediate answer for you. I can go through the instructions you linked to to try and assist you, but I won't have a chance to do so today or tomorrow as I'm preparing lectures for another class. 

In the mean time, If you're stuck and can not proceed forward, you might want to post a question on StackOverflow or https://www.reddit.com/r/aws/ as someone with more experience in EC2 might be able to provide you with a quicker response.

Sorry I don't have more immediate/helpful information to provide regarding this, but I wanted to at least provide some suggestions on how you could troubleshoot this. : )

**Comment by anyav77** [comment]
I created the post on reddit, and I found this post on StackOverflow:
https://stackoverflow.com/questions/43065929/i-cannot-access-my-aws-ec2-server-via-ip

VPC console is a new domain for me.  I had prior experience with Amazon S3, but no experience with EC2.
With that, I'm thinking of refocusing my independent study on learning the differences between Amazon Media Services, instead of testing Laravel on AWS.

Please let me know if you have any suggestions.

**Comment by susanBuck** [comment]
@anyav77 That shift in focus sounds good. 👍
