### ISSUE TITLE
Dusk test fails ExampleTest - APP_URL must include http://

### ISSUE THREAD

**Issue by cjreilly** [susanBuck/e15-spring20#53]
I'm hoping to save anyone some time with this. Dusk fails even basic tests with an error that includes the following lines:
`{path}/vendor/Laravel/dusk/src/Concerns/ProvidesBrowser.php:68`
and
`{path}/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:99`

Solution:
APP_URL must include _http://_ before the site. Presumably if you are using TLS/SSL then it will be _https://_

**Comment by budostylz** [comment]
@cjreilly, you are the man! That was right on time. I was receiving errors following the bookmark example performing the unit tests. Thank you for the help.

V/r,
Shaun

**Comment by susanBuck** [comment]
Great tip @cjreilly - Thanks for taking the time to share!

**Comment by RGPhD** [comment]
Thanks for sharing Christopher.
Robelyn
