### ISSUE TITLE
eCommerce in Laravel?

### ISSUE THREAD

**Issue by anyav77** [susanBuck/e15-spring20#54]
It may be too short of a notice... but is it possible to have a lecture or some information on e-Commerce aspects of Laravel? 
Is it possible to build-in custom shopping cart features in Laravel, without relying of external purchase links? For example, select product feature or a quantity, or buy a downloadable product.  For a book, it could be selecting a language/translation, hard cover, softcover, pdf.

**Comment by susanBuck** [comment]
Sorry, do not have time to fit in a lecture on e-commerce specifically this semester. However, all of the things you listed are features we could build using the strategies we've studied this semester.

In terms of handling transactions, it depends on what credit card merchant you want to use. I typically use [Stripe](https://stripe.com/) and program it via their PHP SDK: [stripe/stripe-php](https://github.com/stripe/stripe-php) which is easily integratable into Laravel. 

Stripe also has lots of "drop in" utilities that make credit card processing straightforward.

Other things to check out: 
+ [AvoRed an Open Source Laravel Shopping Cart](https://www.avored.com/)
+ [Laravel Cashier (Stripe)](https://laravel.com/docs/7.x/billing)
+ [Laravel Cashier (Mollie)](https://github.com/laravel/cashier-mollie)

**Comment by cjreilly** [comment]
You should really implement ssl/tls on your server before considering e-commerce. In fact many payment processing agencies have very strict requirements. Another option is to build the catalog on your site and then link to an external site for purchasing, a lot like the bookmark application. That way you don't even have to assume the risk storing payment information.

**Comment by susanBuck** [comment]
Closing this post due to inactivity, but feel free to continue the discussion or post a new thread if any questions are still pending.
