### ISSUE TITLE
Package wont's install

### ISSUE THREAD

**Issue by anyav77** [susanBuck/e15-spring20#55]
I attempted a test installation of [aws_video](https://packagist.org/packages/andrelohmann-silverstripe/aws_video) on a local server, and I ran into an error.

```git
C:\xampp\htdocs\e15\independent-study\example (master){hg}
λ composer require andrelohmann-silverstripe/aws_video
Using version ^0.2.0 for andrelohmann-silverstripe/aws_video
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
    - Conclusion: install php-ffmpeg/php-ffmpeg 0.6.0
    - Installation request for andrelohmann-silverstripe/aws_video ^0.2.0 -> satisfiable by andrelohmann-silverstripe/aws_video[0.2.0].
    - Conclusion: remove monolog/monolog 2.0.2
    - Conclusion: don't install monolog/monolog 2.0.2
    - php-ffmpeg/php-ffmpeg 0.6.0 requires alchemy/binary-driver ~1.5 -> satisfiable by alchemy/binary-driver[1.5.0, 1.6.0].
    - alchemy/binary-driver 1.5.0 requires monolog/monolog ~1.3 -> satisfiable by monolog/monolog[1.10.0, 1.11.0, 1.12.0, 1.13.0, 1.13.1, 1.14.0, 1.15.0, 1.16.0, 1.17.0, 1.17.1, 1.17.2, 1.18.0, 1.18.1, 1.18.2, 1.19.0, 1.20.0, 1.21.0, 1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.25.0, 1.25.1, 1.25.2, 1.25.3, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.5.0, 1.6.0, 1.7.0, 1.8.0, 1.9.0, 1.9.1, 1.x-dev].
    - alchemy/binary-driver 1.6.0 requires monolog/monolog ^1.3 -> satisfiable by monolog/monolog[1.10.0, 1.11.0, 1.12.0, 1.13.0, 1.13.1, 1.14.0, 1.15.0, 1.16.0, 1.17.0, 1.17.1, 1.17.2, 1.18.0, 1.18.1, 1.18.2, 1.19.0, 1.20.0, 1.21.0, 1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.25.0, 1.25.1, 1.25.2, 1.25.3, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.5.0, 1.6.0, 1.7.0, 1.8.0, 1.9.0, 1.9.1, 1.x-dev].
    - Can only install one of: monolog/monolog[1.12.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.13.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.13.1, 2.0.2].
    - Can only install one of: monolog/monolog[1.14.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.15.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.16.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.17.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.17.1, 2.0.2].
    - Can only install one of: monolog/monolog[1.17.2, 2.0.2].
    - Can only install one of: monolog/monolog[1.18.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.18.1, 2.0.2].
    - Can only install one of: monolog/monolog[1.18.2, 2.0.2].
    - Can only install one of: monolog/monolog[1.19.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.20.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.21.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.22.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.22.1, 2.0.2].
    - Can only install one of: monolog/monolog[1.23.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.24.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.25.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.25.1, 2.0.2].
    - Can only install one of: monolog/monolog[1.25.2, 2.0.2].
    - Can only install one of: monolog/monolog[1.25.3, 2.0.2].
    - Can only install one of: monolog/monolog[1.x-dev, 2.0.2].
    - Can only install one of: monolog/monolog[1.10.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.11.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.3.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.3.1, 2.0.2].
    - Can only install one of: monolog/monolog[1.4.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.4.1, 2.0.2].
    - Can only install one of: monolog/monolog[1.5.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.6.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.7.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.8.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.9.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.9.1, 2.0.2].
    - Installation request for monolog/monolog (locked at 2.0.2) -> satisfiable by monolog/monolog[2.0.2].


Installation failed, reverting ./composer.json to its original content.
```
Is it a problem with the plugin?  Or could it be a conflict with a previously installed plugin,[ laravel-video](https://github.com/imanghafoori1/laravel-video)?

**Comment by susanBuck** [comment]
FYI I'm doing a test of installing this package on my end now. Will follow-up shortly with what I find out.

**Comment by susanBuck** [comment]
[andrelohmann/silverstripe-aws_video](https://github.com/andrelohmann/silverstripe-aws_video) is very outdated - it hasn't been updated in 3 years. 

Specifically, the issue is that one of its subdependencies is trying to use monolog ~1.3, but Laravel is pulling in the current version of monolog which is at v2.

Is there reason you a need a silverstripe-specific AWS video package?

If not, I suggest the official AWS SDK package - https://github.com/aws/aws-sdk-php.

**Comment by anyav77** [comment]
Thank you so much! There is no specific reason why I wanted to use that package.  I'm just trying to explore the options for streaming media.  I believe Amazon is one of the best media streaming hostings platforms, and I'm trying to find out how to connect Laravel to Amazon for media storage, content distribution, and streaming.

I'm about to give it a try, but I'm confused about this requirement: "We highly recommend having it compiled with the cURL extension and cURL 7.16.2+ compiled with a TLS backend (e.g., NSS or OpenSSL)."
Is it something I need to install prior to running composer require aws/aws-sdk-php ?
Or is it included with the composer already?

**Comment by anyav77** [comment]
Also, will it work with the Digital Ocean server, or do I have to have Laravel installed on the Amazon server?

**Comment by susanBuck** [comment]
I checked our production servers and you're good to go with the curl requirement:

```
root@e15:~# curl --version
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
```

To answer your second question - it will work with the DigitalOcean server - or any server. You don't have to use Amazon's server's specifically to interact with AWS.

**Comment by anyav77** [comment]
Thank you!  
I also found this package:
[https://github.com/aws/aws-sdk-php-laravel](https://github.com/aws/aws-sdk-php-laravel)

Is it an alternative for [https://github.com/aws/aws-sdk-php](https://github.com/aws/aws-sdk-php) ?  
Do I need to install both in order to use AWS media services in Laravel?

**Comment by susanBuck** [comment]
aws-sdk-php-laravel is a good package - I use it on a project. 👍

It's basically a layer on top of the aws-sdk-php that makes it easily integratable into your Laravel app. You don't need to install both, because aws-sdk-php-laravel lists aws-sdk-php as one of its dependencies ([ref](https://github.com/aws/aws-sdk-php-laravel/blob/master/composer.json#L16)).

**Comment by susanBuck** [comment]
Closing this post due to inactivity, but feel free to continue the discussion or post a new thread if any questions are still pending.
