### ISSUE TITLE
eager loading with "whereHas query"

### ISSUE THREAD

**Issue by nnoel2626** [susanBuck/e15-spring20#58]
I try to eager load tags with this query below but it does not work. Is there a way to accomplish this? Otherwise, I will have to make another call to the database to get all the tags.

```php
 #Retrieve all $microphones with at least one tag_name containing words installed

        $microphones = Microphone::with('tags')->whereHas('tags', function ($query) use($tags) {

        $query->where('name','Installed');

         })->orderBy('assigned_frequency')

         ->get();

 ```

**Comment by susanBuck** [comment]
Does not work in that it yields an error, or it does not retrieve the data you're expecting?

If it yields an error, what is the error?

Finally, can you share the URL to your Github repository and indicate which file this code is in. I can test on my end.

**Comment by nnoel2626** [comment]
This is the error I am getting:

```php
Undefined variable: tags

```

I can also share GitHub repo:
https://github.com/nnoel2626/e15/tree/master/wirelessMics
It is  the microphone controller methods on installed and portable.

**Comment by susanBuck** [comment]
Thanks @nnoel2626 - Taking a look now - will follow-up shortly.

**Comment by susanBuck** [comment]
The error `Undefined variable: tags` was coming from the line in your query that says `use($tags)`. 

Once I eliminated that, this is what the controller method looked like:

```php
    /**
    * GET / portable-list
    */
    public function portable(Request $request)
    {
        $microphones = Microphone::with('tags')->whereHas('tags', function ($query) {
            $query->where('name', 'Portable');
        })->orderBy('assigned_frequency')->get();

        return view('microphones.portable')->with([
            'microphones' => $microphones
        ]);
    }
```

And then in the view, I was able to iterate through the tags and display them like so:

```
Tags:
@foreach($microphone->tags as $tag) 
    {{ $tag->name }}
@endforeach
```

Here that is in context:
![image](https://user-images.githubusercontent.com/237711/80840993-83db5480-8bcc-11ea-81da-e08232949a47.png)

And here it is rendered:
![image](https://user-images.githubusercontent.com/237711/80841068-a66d6d80-8bcc-11ea-8695-2f5cbdeaf4e7.png)

Let me know if you have any questions about the above!

**Comment by nnoel2626** [comment]
That was fast. Thank you.
Also, can I submit my project name as wirelessMics instead of p3? Would that be ok?

**Comment by susanBuck** [comment]
@nnoel2626 Yes that's fine
