### ISSUE TITLE
git add .

### ISSUE THREAD

**Issue by kreinholz** [susanBuck/e15-spring20#6]
This may be nit-picking to the extreme, but I'm lazy. Instead of using

```
git add --all
```

I've been using

```
git add .
```

And haven't noticed any difference. Saves a whopping 4 keyboard presses. 😉

**Comment by susanBuck** [comment]
4 key presses adds up over time! : ) 

I've been digging in my memory for why I teach it as `--all`. I thought maybe `.` didn't work in Win/Cmder, but I just tested and it does. Maybe I choose `--all` because it's more explicit? 

Either way, I think I'll switch to `.` moving forward. Thanks for sharing @kreinholz!

**Comment by nicholsonjf** [comment]
You can also stage all changes by click the "+" icon next to the "changes" panel in the "Source Control" section in VSCode.

https://code.visualstudio.com/docs/editor/versioncontrol#_git-support

![Screen Shot 2020-02-11 at 6 08 20 PM](https://user-images.githubusercontent.com/4286084/74288082-80d17600-4cf9-11ea-87b9-e6540569648c.png)

**Comment by cjreilly** [comment]
> This may be nit-picking to the extreme, but I'm lazy. Instead of using
> git add --all
> 
> I've been using
> git add .
> 
> And haven't noticed any difference. Saves a whopping 4 keyboard presses. 😉



> This may be nit-picking to the extreme, but I'm lazy. Instead of using
> git add --all
> 
> I've been using
> git add .
> 
> And haven't noticed any difference. Saves a whopping 4 keyboard presses. 😉

To elaborate on this, the dot is a Linux specifier for the current directory. --all is a command line option specific to git. Be careful that you're always adding all the files for your commit from the root git directory.

**Comment by susanBuck** [comment]
@cjreilly Thanks for bringing this up - an important distinction!
