### ISSUE TITLE
textarea in edit form does not refill when using old input value

### ISSUE THREAD

**Issue by nnoel2626** [susanBuck/e15-spring20#60]
Does any body know to retrieve old input value on a textarea for an edit form?  All the other input fields seem to work with no problem except the texture. See below for code sample:

```php
<div class="form-group">
   <label  for="comments">microphone comments</label>
    <textarea class="form-control" rows="4" cols="50" name="comments" id="comments" placeholder="comments" value="{{ old('comments', $microphone->comments) }}" required  autocomplete="comments" autofocus>
     </textarea>
 </div>

```

**Comment by nnoel2626** [comment]
I just found the answer of my problem at this weblink:
https://stackoverflow.com/questions/23327845/laravel-textarea-does-not-refill-when-using-inputold

"textarea does not have a value attribute. Values in textarea should be inside 
<textarea>{{{your old input value}}}</textarea>
 so in my  case I did like so:

```php
<div class="form-group">
   <label  for="comments">microphone comments</label>
      <textarea class="form-control" rows="4" cols="50" name="comments" id="comments" placeholder="comments"  }}" required  autocomplete="comments" autofocus>{{{ old('comments',$microphone->comments) }}}
        </textarea>
</div>
```

**Comment by susanBuck** [comment]
Glad you found your answer. 👍

For reference, here's another example from Bookmark:

[create.blade.php ln 54](https://github.com/susanBuck/e15/blob/master/bookmark/resources/views/books/create.blade.php#L54):

```html
<textarea dusk='description-input' name='description'>{{ old('description') }}</textarea>
```

And [edit.blade.php ln 51](https://github.com/susanBuck/e15/blob/master/bookmark/resources/views/books/edit.blade.php#L51):

```html
 <textarea name='description'>{{ old('description', $book->description) }}</textarea>
```
