### ISSUE TITLE
Rich content editor - general question

### ISSUE THREAD

**Issue by anyav77** [susanBuck/e15-spring20#63]
In my final project, I'd like to build a wiki where authors can publish the articles.  
It's similar to adding a book, but it will need extra formatting for the text (adding images and videos, formatting text, using paragraphs and headings.

So, I believe it will require a rich text editor.
Do you have any suggestions for this?

**Comment by smsummers1** [comment]
I found a few links that might be helpful.
https://laracasts.com/discuss/channels/laravel/best-html-wysiwyg-for-laravel-55?page=1
https://medium.com/maatwebsite/lets-see-wyg-with-these-editors-e5720e91a626
https://artisansweb.net/top-free-rich-text-editor-web-application/

**Comment by susanBuck** [comment]
@smsummers1's suggestions are a good start. There are *a lot* of options when it comes to wyswig/rich text editors. It's a matter of trying them out and deciding which you like best in terms of user experience and implementation/ease of use.

**Comment by anyav77** [comment]
Thank you so much!  I checked the resources, and I thought of starting with TinyMCE, but it requires Node.js which I'm not familiar with.

So, I decided to try Summernote instead.  

I'm also considering:
https://github.com/Vinelab/laravel-editor
https://github.com/UniSharp/laravel-ckeditor
https://artisansweb.net/install-use-ckeditor-laravel/
and other options.

I have a question about the database.  Which datatype should I use?  
I want to try simple html first,  and expand it into image and video upload.  The ultimate goal is to have videos uploaded to Amazon S3 and stream through Cloudfront, but it will probably be done after the end of the semester.

So, to store the article description in HTML format, should I use TEXT?  
Should it be a column withing the articles table?
Some resources recommend setting up a separate table for HTML TEXT BLOB content.

What is the best approach?

**Comment by susanBuck** [comment]
Sorry for the slow follow-up on this one - I missed the notification from your last reply. : )

I would go with one of the TEXT fields - either `TEXT`, `MEDIUMTEXT`, or `LONGTEXT` depending on how big you anticipate the articles being.

Here's a good breakdown of the different text types, including their character limits:
https://www.mysqltutorial.org/mysql-text/

It can be a good idea to decouple fields with large data into their own tables, giving you the option to do faster queries across all articles, and adding in additional queries for the content on specific articles when you need them.

Alternatively, you may also consider storing the HTML content not in the database, but in files on a server (whether it be your own server, Amazon S3, or some other CDN) - and just store the reference paths to those files in the database for the articles.

MySQL tables/relational databases work well for organizing a lot of smaller content, and doing intricate queries against that content. They're not the best option when it comes to storing more longer-form content.

A similar example can be seen with storing image data - technically you can store the byte data for an image in a table via the BLOB field type, but it's much more efficient to store images on a file server and just reference them from the table.

**Comment by anyav77** [comment]
Thank you so much!  It really helps.

I'm trying to create a system that shows part of the content for guests, and longer articles for logged in users.

I'm trying to decide how much content to show at each stage.

I asked a writer to write a sample article, which happened to be:
599 words
2,982 characters (no spaces)
3,572 characters (with spaces)

I could use it as a guest article, and ask him to create a longer version for registered users.
Alternatively, I could ask him to create an abstract paragraph or two of this article.

What do you recommend from the technology standpoint?

I also have a question on how to implement it with Middleware and file upload, but I will create a separate threat for this.

**Comment by anyav77** [comment]
So, to sum it up:

- guest - abstract article (approx 1-2 paragraphs, no rich text, coming from article column in articles table)
- logged in user - one-page article (approx. 600 words), rich text, coming from a file referenced in the articles table.
- member or logged in user/one time purchase - full artcle (PDF?) or book, coming from a file referenced in the articles table

Do you have any suggestions, based on this?

Technical questions:

1. What is the strategy for uploading the longer text to a server as a file?
2. Is there a way to generate PDFs or html pages based on the rich text content?

**Comment by susanBuck** [comment]
> What is the strategy for uploading the longer text to a server as a file?

You'll want to dog into Laravel's File Storage functionality: https://laravel.com/docs/7.x/filesystem#introduction

I'm envisioning a page/form with a long form textarea the author can write into. Upon hitting "Add" a unique file name is generated, and using the File Storage functionality referenced above, the content is written to a file on disk.

Also, a row in an `articles` table (or something similar) would be created recording details such as the file name, author info, title, created_at, updated_at, etc. for any other meta data you need.


> is there a way to generate PDFs or html pages based on the rich text content?

Yup! There are several different packages that can do this, but I've been using <https://github.com/barryvdh/laravel-dompdf> for years with good success.

Below is an example controller method from one of my apps that uses it. It's very similar to returning a view - except the content comes as a downloadable PDF.

```php
/**
 * Show an individual transaction
 */
public function transaction(Request $request, $txn_id = null)
{
    $transaction = Transaction::where('id_app', $txn_id)->first();

    if (! $transaction) {
        return redirect()->route('accounts.transactions')->with('alert', [
            'type' => 'error',
            'message' => 'Transaction '.$txn_id.' not found.', ]);
    }

    $action = new ShowTransaction($request->user(), $transaction);

    $pdf = PDF::loadView('accounts.transactionPdf', $action->vda);

    return $pdf->download('introze-receipt-'.$txn_id.'.pdf');

    // When testing/quickly previewing the content, we can load the content directly in the browser by commenting out the above line and uncommenting this line:
    //return view('accounts.transactionPdf')->with($action->vda);
}
```
