### ISSUE TITLE
Small Image Issue

### ISSUE THREAD

**Issue by smsummers1** [susanBuck/e15-spring20#65]
My issue is that I have a Bloomz icon in the bottom left hand side of my screen in my master.blade.php file that breaks only when I navigate to the following pages:

- /editStudent/{id}

- /reports/listVolunteers

- /reports/studentHours

The strange thing is that all the other images and links in my master.blade.php file remain steadfast, but not the Bloomz icon.  Any thoughts?

Can I post the link to my application?  This issue might not make sense without visually seeing what is occurring?

**Comment by smsummers1** [comment]
Nevermind.....I figured it out.

**Comment by susanBuck** [comment]
Glad you got it sorted out @smsummers1. : )

(For future reference - yes, you can post links to your application)
