### ISSUE TITLE
P3 seeders requirement

### ISSUE THREAD

**Issue by nicholsonjf** [susanBuck/e15-spring20#66]
The P3 spec states that seeders are required for all tables. Does this include:

- failed_jobs
- password_resets

Apologies if this has already been answered somewhere, I looked around and couldn't find anything about it.

Thanks!
James

**Comment by smsummers1** [comment]
I did not create seeders for those tables.

**Comment by susanBuck** [comment]
No, seeders are only required for tables you make/use (including `users`)

**Comment by nicholsonjf** [comment]
Thank you for clarifying. Closing this.
