### ISSUE TITLE
Warning ⚠️ Don't Use PHP Reserved Words to Name Models 

### ISSUE THREAD

**Issue by nicholsonjf** [susanBuck/e15-spring20#67]
I made the unfortunate mistake of naming one of my models "List" which is [reserved by PHP](https://www.php.net/manual/en/reserved.keywords.php). When I tried running my seeders I kept getting a cryptic syntax error 

`syntax error, unexpected 'List' (T_LIST), expecting identifier (T_STRING) or '{'`

for this line

`use App\List;`

I just spent the last two hours renaming tables/foreign keys/columns etc. Don't be like me, avoid PHP reserved words when naming your models 😁

**Comment by susanBuck** [comment]
Ouch - the bugs where the error messages are so far in left field are the worst. Glad you eventually got to the bottom of it. : )
