### ISSUE TITLE
Query works on Local but not Production

### ISSUE THREAD

**Issue by budostylz** [susanBuck/e15-spring20#71]
I have an orders table query which works fine on local. When I deploy to production however the query breaks and give me a server error. I'll work on resolving this before submission today. I know this is short notice and apologies.

**Comment by susanBuck** [comment]
I can more effectively help you with more details.

What is the error?
What query is causing the error?
What is your repo URL?

**Comment by budostylz** [comment]
Thanks for the quick response Susan. Below are the details:
Server error is 500

Query that is causing the error is:
$orders = Order::distinct()->select('user_id')->where('status', '=', null)->orderBy('updated_at', 'desc')->get();

Route triggering the error is : /bartenderreview
Action triggering the error is : app/Actions/BartenderReview/GetCustomer

Location url where error is occuring is : http://e15p3.budoapps.com/bartenderreview
I'm currently debugging the error and outputting some debug code.

V/r,
Shaun

**Comment by budostylz** [comment]
I notice I get the 500 when I use the get() at the end of the Orders query.

**Comment by budostylz** [comment]
Think I got it. I had to break out the queries like this:

$userOrder = Order::distinct()->select('user_id')->get();
$orders = $userOrder->where('status', '=', null);

However, its not liking my order by. I'll work on this piece. Thank you very much for the help and response Susan. 

V/r,
Shaun

**Comment by susanBuck** [comment]
Sounds like you're making progress. : ) I do see http://e15p3.budoapps.com/bartenderreview is loading now.

Tip: When getting a error on production, check `storage/logs/laravel.log` within the app directory on production for more context/clues.

**Comment by susanBuck** [comment]
FYI: Was testing on my end locally and the following code with the query all on one line and with the `orderBy` included worked:

```php
<?php

namespace App\Actions\BartenderReview;

use App\User;
use App\Order;

class GetCustomer
{
    public function __construct()
    {
        $orders = Order::distinct()
            ->select('user_id')
            ->where('status', '=', null)
            ->orderBy('updated_at', 'desc')
            ->get();

        dump($orders);

        foreach ($orders as $order) {
            $user_id = $order->user_id;
            $user_title = User::where('id', '=', $user_id)->get()->first()->user_name;
            $userArr[$user_id] = $user_title;
        }

        $this->userArr = $userArr;
    }
}
```

![image](https://user-images.githubusercontent.com/237711/81685194-e2eb6580-9425-11ea-92f2-3904e53ff304.png)

If this same code isn't working on your end still, let me know.

**Comment by budostylz** [comment]
Super weird. I found this error at the log path you gave me. 

[2020-05-12 11:23:20] local.ERROR: SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'barapp.orders.updated_at' which is not in SELECT list; this is incompatible with DISTINCT (SQL: select distinct `user_id` from `orders` where `status` is null order by `updated_at` desc) {"userId":1,"exception":"[object] (Illuminate\\Database\\QueryException(code: HY000): SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'barapp.orders.updated_at' which is not in SELECT list; this is incompatible with DISTINCT (SQL: select distinct `user_id` from `orders` where `status` is null order by `updated_at` desc) at /var/www/html/e15/e15p3/vendor/laravel/framework/src/Illuminate/Database/Connection.php:671)


I tried the order by code and it's not working on my end. This one is a puzzler. 

V/r,
Shaun

**Comment by susanBuck** [comment]
I did a little more digging into this and learned that different versions of MySQL have different rules on whether you can order by data that is not included in your select.

This explains why it was working locally but not on production - minor MySQL version differences. : )

To fix, you should update the select so it's getting not only the `user_id`, but also the `updated_at` which is what you're trying to order by:

```php
$orders =  Order::distinct()
            ->select('user_id', 'updated_at')
            ->where('status', '=', null)
            ->orderBy('updated_at', 'desc')
            ->get();
```

I ran some tests on production and confirmed that when I didn't have `updated_at`, it threw the same error you were seeing, but upon adding it, the error went away.

Apologies for not doing a more thorough dig on this in my first replies - I should have tested on production and not assumed it was just an underlying problem with the query. : )

**Comment by budostylz** [comment]
Very cool Susan. Thank you very much for this. I'll make changes to the code on my end and will update production after the project is graded. See you in the Vue course this coming fall.

V/r,
Shaun

**Comment by susanBuck** [comment]
Sounds good. Glad to have you in class again in the upcoming semester!
