### ISSUE TITLE
Laravel Dusk Tests Resets All Database Tables Except Users

### ISSUE THREAD

**Issue by budostylz** [susanBuck/e15-spring20#72]
I'm running dusk tests and for some reason the tests failed with my tables being cleared. This occurs when I test registration. Users can register fine without the tests. I used both model factory and seeding approaches. The strange thing happens when a user is created in the users table after registration and all other tables are cleared. I'm working on figuring this one out. It's been a really fun so far, LoL!

Below is the error I am receiving after running the tests.

Caused by
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN KEY `users_user_id_foreign`; check that it exists

**Comment by budostylz** [comment]
Never mind, Don't add any use statements within your test classes. LOL! Looks like it's functioning again properly.

**Comment by budostylz** [comment]
use DatabaseMigrations;
use withFaker;

Using the two namespaces above within my AuthTest Dusk classes wipes out my database tables except users. I was able to test successfully using just the 'withFaker' namespace within my test class without the tables wiping out. Now I'm able to test with my model factories. I see the reason for namespaces to be within test classes, good talk. LoL!

**Comment by susanBuck** [comment]
Confirming the `use DatabaseMigrations` line will force your tables to be reset after each test. : )

More info on that here: https://laravel.com/docs/7.x/database-testing#resetting-the-database-after-each-test
