### ISSUE TITLE
Restricting part of the content on the page - best approach? Re: Rich content editor quetion

### ISSUE THREAD

**Issue by anyav77** [susanBuck/e15-spring20#73]
This is related to the previous two questions on Middleware and Rich content editor.

I'm trying to create a system where the guest users see part of the content in the articles, and have to login to see the full article.

In my routes, I have:
```php
Route::group(['middleware' => 'auth'], function () {
// some routes
});

# View Article
Route::get('/wiki/{id}/{slug}', 'WikiController@show');
```
Do I need to create a separate route and group for the longer articles?

```php
Route::group(['middleware' => 'auth'], function () {
// some routes
});

# View Article 
Route::get('/wiki/{id}/{slug}', 'WikiController@show');

# View Article - Expanded
Route::get('/wiki/{id}/{slug}/f', 'WikiController@showfull');
```
or should I use `@guest` or `@if(!Auth::$user` on `Route::get('/wiki/{id}/{slug}',`?

Also, should I modify the form into two sections:
abstract/short article
full article?

Or is there a way to do it automatically by word count?

**Comment by susanBuck** [comment]
**Re: Q1**

The two ways you've described of setting it up would work, so it comes down to personal preference.

My preference would be not to have a separate route for the expanded version of the article - it'd be nicer to keep the URL clean.

So I would use the same route, and build the logic of what to display into the controller method, depending on whether the visitor is logged in or not.


**Re: Q2**
You can dynamically truncate the full article into the abstract. Check out Marvel's `word` string helper: https://laravel.com/docs/7.x/helpers#method-str-words

This will let you truncate the text by a certain word count, and you can even specify a character ending for the truncated text such as elipsses (`...`)
