### ISSUE TITLE
Restricting content editing to authors

### ISSUE THREAD

**Issue by anyav77** [susanBuck/e15-spring20#74]
This is related to the previous questions on the articles.
I'd like to limit the "edit article" option to the author of the article.
The article may have two or more authors.

What is the best approach for this?  Does it involve creating groups for authenticated users?

I was thinking to create a table 'authors' that connects to the users table and articles table.
In the form, the user may submit a co-author.
The controller will detect user info and add it to the authors' table.

Please let me know if I'm missing anything.

**Comment by susanBuck** [comment]
> The article may have two or more authors.
> I was thinking to create a table 'authors' that connects to the users table and articles table.

Sounds like a good use case for the *many to many* relationship.

You could call the pivot table `article_user`, or, you can override that expected naming convention and call it `authors` if that feels more intuitive.

Here's the snippet from the docs explaining how to use a customized pivot table name:

![image](https://user-images.githubusercontent.com/237711/81836994-39ce6900-9512-11ea-8417-d2a80541c683.png)

Ref: https://laravel.com/docs/7.x/eloquent-relationships#many-to-many
