### ISSUE TITLE
Outro

### ISSUE THREAD

**Issue by budostylz** [susanBuck/e15-spring20#75]
Thank you for a great learning experience Susan. I have jump the hurdles and finally completed project 3. Thank you for taking the time out to help and helping me improve my skills as a professional web developer. Lastly, thanks to all the great students in this course. Good luck and bless on your future missions. Stay Bless, V/r, Shaun

**Comment by susanBuck** [comment]
@budostylz - And thank you for all your hard work. : ) Best of luck for you moving forward as well!
