### ISSUE TITLE
Public Key Denied??

### ISSUE THREAD

**Issue by janenycxo** [susanBuck/e15-spring20#8]
Hi Susan and E15 2020,

I am encountering a ssh permission issue. I have set up my production server on DigitalOcean, created a created a LAMP droplet and added the new SSH key that is the same as my Github e15.pub but am unable to ssh into DigitalOcean via Cmder.

I double checked the ssh key on DigitalOcean with cat ~/.ssh/id_rsa.pub and they match up.

C:\xampp\htdocs\e15 (master){hg}
λ ssh root@165.227.187.253
root@165.227.187.253: Permission denied (publickey).

Then when I test it -
C:\xampp\htdocs\e15 (master){hg}
λ ssh -T git@github.com
Hi janenycxo! You've successfully authenticated, but GitHub does not provide shell access.

Please chime in if you can help troubleshoot. I am not sure why there is an error. 
Thanks!!
Jane

**Comment by susanBuck** [comment]
Hi @janenycxo -

I can help you get this straightened out. First, a couple points of clarification...

You said you created the Droplet with your `e15.pub` key, but then when you said you checked it you referred to `id_rsa.pub`. Just to be clear, `id_rsa.pub` is the key we create on the DigitalOcean server to allow it to connect to Github.com. It's not the key used to connect between your computer and your DigitalOcean server.

Additionally, when you run the test command `ssh -T git@github.com` that's confirming the computer/server from which you're running that command can connect to Github.com. It's irrelevant to the connection between your computer and your DigitalOcean server.

Those notes aside...

9 times out of 10, a permission denied error occurs when the SSH key was not correctly added during the Droplet creation process. 

There is a way to add a SSH key after a Droplet is created, but it's a tedious process. Given that, it's easiest just to delete the existing Droplet and then create a new one, retracing your steps and double checking the step where you add the SSH key. (For reference, I have a set of notes in the appendix addressing this: [DigitalOcean - Permission denied](https://hesweb.dev/e15/notes/appendix/permission-denied)).

If after creating a new Droplet you're still getting "permission denied" let me know - we can set up a time to connect/screenshare and dig into what else could be causing this problem. : )

**Comment by janenycxo** [comment]
Hi Susan,

Before I deleted the droplet, I tried and was able to access the console though I ultimately decided to create an entirely new droplet with new SSH key. 

P1 is up and running as it should, and I always appreciate working these out and troubleshooting.  Sometimes I get more confused, and most times I actually learn a thing or two.

Much thanks!
Jane

**Comment by susanBuck** [comment]
Glad you got it sorted out! : )
